/**
 * Tests for scripts/doctor.js
 */
const assert = require('assert'); const fs = require('fs'); const os = require('os'); const path = require('path'); const { execFileSync } = require('child_process');
const SCRIPT = path.join(__dirname, '..', '..', 'scripts', 'doctor.js'); const REPO_ROOT = path.join(__dirname, '..', '..');
const CURRENT_PACKAGE_VERSION = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'package.json'), 'utf8')).version; const CURRENT_MANIFEST_VERSION = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'manifests', 'install-modules.json'), 'utf8')).version; const { createInstallState, writeInstallState } = require('../../scripts/lib/install-state');
function createTempDir(prefix) { return fs.mkdtempSync(path.join(os.tmpdir(), prefix)); } function cleanup(dirPath) { fs.rmSync(dirPath, { recursive: true, force: true }); } function writeState(filePath, options) { const state = createInstallState(options); writeInstallState(filePath, state); }
function run(args = [], options = {}) { try { const stdout = execFileSync('node', [SCRIPT, ...args], { cwd: options.cwd, env: { ...process.env, HOME: options.homeDir || process.env.HOME }, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], timeout: 10000 }); return { code: 0, stdout, stderr: '' }; } catch (error) { return { code: error.status || 1, stdout: error.stdout || '', stderr: error.stderr || '' }; } }
function test(name, fn) { try { fn(); console.log(`  ✓ ${name}`); return true; } catch (error) { console.log(`  ✗ ${name}`); console.log(`    Error: ${error.message}`); return false; } }

console.log('\n=== Testing doctor.js ===\n'); let passed = 0; let failed = 0;
if (test('reports a healthy project install with exit code 0', () => { const projectRoot = createTempDir('doctor-project-'); try { const canonicalProjectRoot = fs.realpathSync(projectRoot); const statePath = path.join(canonicalProjectRoot, '.factory', 'install-state.json'); const managedFile = path.join(canonicalProjectRoot, '.factory', 'rules', 'common', 'coding-style.md'); fs.mkdirSync(path.dirname(managedFile), { recursive: true }); fs.mkdirSync(path.dirname(statePath), { recursive: true }); fs.writeFileSync(managedFile, fs.readFileSync(path.join(REPO_ROOT, 'rules', 'common', 'coding-style.md'), 'utf8')); writeState(statePath, { adapter: { id: 'factory-droid-project', target: 'factory-droid', kind: 'project' }, targetRoot: canonicalProjectRoot, installStatePath: statePath, request: { profile: null, modules: ['rules-core'], includeComponents: [], excludeComponents: [], legacyLanguages: [], legacyMode: false }, resolution: { selectedModules: ['rules-core'], skippedModules: [] }, operations: [{ kind: 'copy-file', moduleId: 'rules-core', sourceRelativePath: 'rules/common/coding-style.md', destinationPath: managedFile, strategy: 'preserve-relative-path', ownership: 'managed', scaffoldOnly: false }], source: { repoVersion: CURRENT_PACKAGE_VERSION, repoCommit: 'abc123', manifestVersion: CURRENT_MANIFEST_VERSION } }); const result = run(['--target', 'factory-droid'], { cwd: projectRoot }); assert.strictEqual(result.code, 0, result.stderr); assert.ok(result.stdout.includes('Status: OK')); } finally { cleanup(projectRoot); } })) passed++; else failed++;
if (test('reports issues for unhealthy installs', () => { const projectRoot = createTempDir('doctor-project-'); try { const statePath = path.join(projectRoot, '.factory', 'install-state.json'); fs.mkdirSync(path.dirname(statePath), { recursive: true }); writeState(statePath, { adapter: { id: 'factory-droid-project', target: 'factory-droid', kind: 'project' }, targetRoot: projectRoot, installStatePath: statePath, request: { profile: 'core', modules: ['rules-core'], legacyLanguages: [], legacyMode: false }, resolution: { selectedModules: ['rules-core'], skippedModules: [] }, operations: [{ kind: 'copy-file', moduleId: 'rules-core', sourceRelativePath: 'rules/common/coding-style.md', destinationPath: path.join(projectRoot, '.factory', 'rules', 'common', 'coding-style.md'), strategy: 'preserve-relative-path', ownership: 'managed', scaffoldOnly: false }], source: { repoVersion: CURRENT_PACKAGE_VERSION, repoCommit: 'abc123', manifestVersion: CURRENT_MANIFEST_VERSION } }); const result = run(['--target', 'factory-droid', '--json'], { cwd: projectRoot }); assert.strictEqual(result.code, 1); const parsed = JSON.parse(result.stdout); assert.strictEqual(parsed.summary.errorCount, 1); } finally { cleanup(projectRoot); } })) passed++; else failed++;
console.log(`\nResults: Passed: ${passed}, Failed: ${failed}`); process.exit(failed > 0 ? 1 : 0);
