/**
 * Tests for scripts/list-installed.js
 */
const assert = require('assert'); const fs = require('fs'); const os = require('os'); const path = require('path'); const { execFileSync } = require('child_process');
const SCRIPT = path.join(__dirname, '..', '..', 'scripts', 'list-installed.js'); const REPO_ROOT = path.join(__dirname, '..', '..'); const CURRENT_PACKAGE_VERSION = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'package.json'), 'utf8')).version; const CURRENT_MANIFEST_VERSION = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'manifests', 'install-modules.json'), 'utf8')).version; const { createInstallState, writeInstallState } = require('../../scripts/lib/install-state');
function createTempDir(prefix) { return fs.mkdtempSync(path.join(os.tmpdir(), prefix)); } function cleanup(dirPath) { fs.rmSync(dirPath, { recursive: true, force: true }); } function writeState(filePath, options) { const state = createInstallState(options); writeInstallState(filePath, state); }
function run(args = [], options = {}) { try { const stdout = execFileSync('node', [SCRIPT, ...args], { cwd: options.cwd, env: { ...process.env, HOME: options.homeDir || process.env.HOME }, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], timeout: 10000 }); return { code: 0, stdout, stderr: '' }; } catch (error) { return { code: error.status || 1, stdout: error.stdout || '', stderr: error.stderr || '' }; } }
function test(name, fn) { try { fn(); console.log(`  ✓ ${name}`); return true; } catch (error) { console.log(`  ✗ ${name}`); console.log(`    Error: ${error.message}`); return false; } }
console.log('\n=== Testing list-installed.js ===\n'); let passed = 0; let failed = 0;
if (test('reports when no install-state files are present', () => { const projectRoot = createTempDir('list-installed-project-'); try { const result = run([], { cwd: projectRoot }); assert.strictEqual(result.code, 0); assert.ok(result.stdout.includes('No EFD install-state files found')); } finally { cleanup(projectRoot); } })) passed++; else failed++;
if (test('emits JSON for discovered factory-droid install-state records', () => { const projectRoot = createTempDir('list-installed-project-'); try { const statePath = path.join(projectRoot, '.factory', 'install-state.json'); writeState(statePath, { adapter: { id: 'factory-droid-project', target: 'factory-droid', kind: 'project' }, targetRoot: projectRoot, installStatePath: statePath, request: { profile: 'core', modules: [], legacyLanguages: [], legacyMode: false }, resolution: { selectedModules: ['rules-core'], skippedModules: [] }, operations: [], source: { repoVersion: CURRENT_PACKAGE_VERSION, repoCommit: 'abc123', manifestVersion: CURRENT_MANIFEST_VERSION } }); const result = run(['--json'], { cwd: projectRoot }); assert.strictEqual(result.code, 0, result.stderr); const parsed = JSON.parse(result.stdout); assert.strictEqual(parsed.records.length, 1); assert.strictEqual(parsed.records[0].state.target.id, 'factory-droid-project'); } finally { cleanup(projectRoot); } })) passed++; else failed++;
console.log(`\nResults: Passed: ${passed}, Failed: ${failed}`); process.exit(failed > 0 ? 1 : 0);
