/**
 * Tests for scripts/uninstall.js
 */
const assert = require('assert'); const fs = require('fs'); const os = require('os'); const path = require('path'); const { execFileSync } = require('child_process');
const INSTALL_SCRIPT = path.join(__dirname, '..', '..', 'scripts', 'install-apply.js'); const SCRIPT = path.join(__dirname, '..', '..', 'scripts', 'uninstall.js');
function createTempDir(prefix) { return fs.mkdtempSync(path.join(os.tmpdir(), prefix)); } function cleanup(dirPath) { fs.rmSync(dirPath, { recursive: true, force: true }); }
function run(args = [], options = {}) { try { const stdout = execFileSync('node', [SCRIPT, ...args], { cwd: options.cwd, env: { ...process.env, HOME: options.homeDir || process.env.HOME }, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], timeout: 10000 }); return { code: 0, stdout, stderr: '' }; } catch (error) { return { code: error.status || 1, stdout: error.stdout || '', stderr: error.stderr || '' }; } }
function test(name, fn) { try { fn(); console.log(`  ✓ ${name}`); return true; } catch (error) { console.log(`  ✗ ${name}`); console.log(`    Error: ${error.message}`); return false; } }
console.log('\n=== Testing uninstall.js ===\n'); let passed = 0; let failed = 0;
if (test('uninstalls files from a real factory-droid install and preserves unrelated files', () => { const homeDir = createTempDir('uninstall-home-'); const projectRoot = createTempDir('uninstall-project-'); try { execFileSync('node', [INSTALL_SCRIPT, 'typescript'], { cwd: projectRoot, env: { ...process.env, HOME: homeDir }, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], timeout: 10000 }); const managedPath = path.join(projectRoot, '.factory', 'rules', 'common', 'coding-style.md'); const statePath = path.join(projectRoot, '.factory', 'install-state.json'); const unrelatedPath = path.join(projectRoot, 'custom-user-note.txt'); fs.writeFileSync(unrelatedPath, 'leave me alone'); const result = run(['--target', 'factory-droid'], { cwd: projectRoot, homeDir }); assert.strictEqual(result.code, 0, result.stderr); assert.ok(!fs.existsSync(managedPath)); assert.ok(!fs.existsSync(statePath)); assert.ok(fs.existsSync(unrelatedPath)); } finally { cleanup(homeDir); cleanup(projectRoot); } })) passed++; else failed++;
console.log(`\nResults: Passed: ${passed}, Failed: ${failed}`); process.exit(failed > 0 ? 1 : 0);
